Day_52/EduWiki/EduWiki/ViewModels/CourseViewModel.cs
using System.Collections.Generic;

namespace EduWiki.ViewModels
{
    public class CourseViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Faculty { get; set; }
        public int ECTS { get; set; }
    }
}

Day_52/EduWiki/EduWiki/ViewModels/LecturerIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EduWiki.ViewModels
{
    public class LecturerIndexViewModel
    {
        public List<LecturerViewModel> Lecturers { get; set; }
    }
}

Day_52/EduWiki/EduWiki/ViewModels/LecturerViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EduWiki.ViewModels
{
    public class LecturerViewModel
    {
        public int Id { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage ="Invalid email format")]
        public string Email { get; set; }
        [Required]
        public string Phone { get; set; }
        public List<CourseViewModel> Courses { get; set; }
        public string AboutText { get; set; }
        public string ImagePath { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }
    }
}

Day_52/EduWiki/EduWiki/Controllers/HomeController.cs
using EduWiki.Services.Abstractions;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EduWiki.Controllers
{
    [Route("[controller]")]
    public class HomeController : Controller
    {
        private readonly ILecturerService _lecturerService;
        public HomeController(ILecturerService lecturerService)
        {
            _lecturerService = lecturerService;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Day_52/EduWiki/EduWiki/Controllers/LecturersController.cs
using EduWiki.Data;
using EduWiki.Services.Abstractions;
using EduWiki.Services.Models;
using EduWiki.ViewModels;
using Mapster;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EduWiki.Controllers
{
    public class LecturersController : Controller
    {

        private readonly ILecturerService _service;
        private readonly IFileService _fileService;

        public LecturersController(ILecturerService service, IFileService fileManager)
        {
            _service = service;
            _fileService = fileManager;
        }

        public async Task<ActionResult> Index()
        {
            var lecturers = await _service.GetAllAsync();

            var result = new LecturerIndexViewModel
            {
                Lecturers = lecturers.Adapt<List<LecturerViewModel>>()
            };

            return View(result);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(LecturerViewModel lecturerVM)
        {
            if (ModelState.IsValid)
            {
                // მესმის რომ ქვედა ლაინი LecturerService-ში გადატანა აჯობებდა, 
                // უბრალოდ IFormFile-ს სერვის ლეიერში მაპინგის დროს ბევრ პრობლემას შევეჩეხე, netstandard-ის ვერსიებზე მიგდებდა ერორებს და აღარ ჩავეძიე
                lecturerVM.ImagePath = await _fileService.UploadAsync(lecturerVM.ImageFile);
                var lecturer = lecturerVM.Adapt<LecturerServiceModel>();
                await _service.CreateAsync(lecturer);

                // მეორე სერვისიც მხოლოდ იმიტომ გამოვიძახე აქ რომ viewbagს სხვანაირად ვერ ვაყოლებდი ინდექსში
                ViewBag.Success = true;
                var lecturersList = await _service.GetAllAsync();
                var indexVM = new LecturerIndexViewModel
                {
                    Lecturers = lecturersList.Adapt<List<LecturerViewModel>>()
                };
                return View("Index", indexVM);
            }
            else
            {
                //ModelState.Clear();
                ModelState.AddModelError("ModelError", "Incorrect data format");
                return View(lecturerVM);
            }
        }

        public async Task<ActionResult> Details(int id)
        {
            var lecturer = (await _service.GetAsync(id)).Item2;
            var lecturerVM = lecturer.Adapt<LecturerViewModel>();
            return View(lecturerVM);
        }

        [HttpPost]
        public async Task<ActionResult> Details(LecturerViewModel lecturerVM)
        {
            if (ModelState.IsValid)
            {
                var lecturer = lecturerVM.Adapt<LecturerServiceModel>();
                await _service.UpdateAsync(lecturer);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                //ModelState.Clear();
                ModelState.AddModelError("ModelError", "Incorrect data format");
                return View(lecturerVM);
            }
        }

        [HttpDelete]
        public async Task<ActionResult> Delete(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

Day_52/EduWiki/EduWiki/Views/Home/Index.cshtml
Home page

Day_52/EduWiki/EduWiki/Views/Lecturers/Create.cshtml
@model EduWiki.ViewModels.LecturerViewModel

<hr />
<div class="container">
    <div class="row">
        <div class="col-md-5">
            @using (Html.BeginForm("Create", "Lecturers", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <table id="tbl" cellpadding="0" cellspacing="0">
                    <tr>
                        <th colspan="4" align="center">Lecturer</th>
                    </tr>
                    <tr>
                        <td>FirstName: </td>
                        <td>
                            <input asp-for="FirstName" class="form-control m-input" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </td>
                    </tr> 
                    <tr>
                        <td>LastName: </td>
                        <td>
                            <input asp-for="LastName" class="form-control m-input" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <td>Email: </td>
                        <td>
                            <input asp-for="Email" class="form-control m-input" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <td>Phone: </td>
                        <td>
                            <input asp-for="Phone" class="form-control m-input" />
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <td>Photo: </td>
                        <td>
                            <input asp-for="ImageFile" class="form-control m-input" />
                        </td>
                    </tr>
                    <tr>
                        <td>About: </td>
                        <td>
                            <input asp-for="AboutText" class="form-control m-input" />
                            <span asp-validation-for="AboutText" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <td>Course Name: </td>
                        <td>
                            <input type="text" class="form-control m-input" name="Courses[0].Name" id="Courses[0].Name" />
                            <span asp-validation-for="Courses[0].Name" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <td>Course Faculty: </td>
                        <td>
                            <input type="text" class="form-control m-input" name="Courses[0].Faculty" id="Courses[0].Faculty" />
                            <span asp-validation-for="Courses[0].Faculty" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <td>Course ECTS: </td>
                        <td>
                            <input type="number" class="form-control m-input" name="Courses[0].ECTS" id="Courses[0].ECTS" />
                            <span asp-validation-for="Courses[0].ECTS" class="text-danger"></span>
                        </td>
                    </tr>
                </table>
                <button id="addRow" type="button" class="btn btn-info">Add Course</button>
                <input type="submit" value="Submit" />
            }
        </div>
    </div>
</div>

<script type="text/javascript">
    

    let count = 1;
    $("#addRow").click(function () {
        var html = '';
        html += '<tr><td>Course Name: </td>';
        html += '<td><input type="text" class="form-control m-input" name="Courses[';
        html += count;
        html += '].Name" /></td></tr>';
        html += '<tr><td>Course Faculty: </td>';
        html += '<td><input type="text" class="form-control m-input" name="Courses[';
        html += count;
        html += '].Faculty"/></td></tr>';
        html += '<tr><td>Course ECTS: </td>';
        html += '<td><input type="number" class="form-control m-input" name="Courses[';
        html += count;
        html += '].ECTS"/></td></tr>';

        count += 1;
        $('#tbl').append(html);
    });
</script>

Day_52/EduWiki/EduWiki/Views/Lecturers/Details.cshtml
@model EduWiki.ViewModels.LecturerViewModel

<hr />
<div class="container">
    <div class="row">
        <div class="col-md-5">
            @using (Html.BeginForm("Details", "Lecturers", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <table id="tbl" cellpadding="0" cellspacing="0">
                    <tr>
                        <th colspan="4" align="center">Lecturer</th>
                    </tr>
                    <tr>
                        <td>FirstName: </td>
                        <td>
                            <input asp-for="FirstName" class="form-control m-input" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <td>LastName: </td>
                        <td>
                            <input asp-for="LastName" class="form-control m-input" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <td>Email: </td>
                        <td>
                            <input asp-for="Email" class="form-control m-input" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <td>Phone: </td>
                        <td>
                            <input asp-for="Phone" class="form-control m-input" />
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <td>About: </td>
                        <td>
                            <input asp-for="AboutText" class="form-control m-input" />
                            <span asp-validation-for="AboutText" class="text-danger"></span>
                        </td>
                    </tr>
                    @foreach (var course in Model.Courses)
                    {
                        var courseIndex = Model.Courses.IndexOf(course);
                        <tr>
                            <td>Course Name: </td>
                            <td>
                                <input type="hidden" class="form-control m-input" name="Courses[@courseIndex].Id" id="Courses[@courseIndex].Id" value="@course.Id" />

                                <input type="text" class="form-control m-input" name="Courses[@courseIndex].Name" id="Courses[@courseIndex].Name" value="@course.Name" />
                            </td>
                        </tr>
                        <tr>
                            <td>Course Faculty: </td>
                            <td>
                                <input type="text" class="form-control m-input" name="Courses[@courseIndex].Faculty" id="Courses[@courseIndex].Faculty" value="@course.Faculty" />
                            </td>
                        </tr>
                        <tr>
                            <td>Course ECTS: </td>
                            <td>
                                <input type="number" class="form-control m-input" name="Courses[@courseIndex].ECTS" id="Courses[@courseIndex].ECTS" value="@course.ECTS" />
                            </td>
                        </tr>
                    }
                    <input type="hidden" id="CoursesCount" value="@Model.Courses.Count" />
                    <input type="hidden" asp-for="ImagePath" />
                </table>
                <button id="addRow" type="button" class="btn btn-info">Add Course</button>
                <input type="submit" value="Submit" />
            }
        </div>
    </div>
</div>

<script type="text/javascript">


    let count = document.getElementById("CoursesCount").value;
    $("#addRow").click(function () {
        var html = '';
        html += '<tr><td>Course Name: </td>';
        html += '<td><input type="text" class="form-control m-input" name="Courses[';
        html += count;
        html += '].Name" /></td></tr>';
        html += '<tr><td>Course Faculty: </td>';
        html += '<td><input type="text" class="form-control m-input" name="Courses[';
        html += count;
        html += '].Faculty"/></td></tr>';
        html += '<tr><td>Course ECTS: </td>';
        html += '<td><input type="number" class="form-control m-input" name="Courses[';
        html += count;
        html += '].ECTS"/></td></tr>';

        count = parseInt(count) + 1;
        $('#tbl').append(html);
    });
</script>

Day_52/EduWiki/EduWiki/Views/Lecturers/Index.cshtml
@model LecturerIndexViewModel

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/css/materialdesignicons.css" integrity="sha256-NAxhqDvtY0l4xn+YVa6WjAcmd94NNfttjNsDmNatFVc=" crossorigin="anonymous" />
<div class="container">
    <div class="content lecturer-list">
        <div class="card card-default">
            <div class="card-header align-items-center px-3 px-md-5">
                <h2>Lecturers</h2>
                <a asp-action="Create"><button type="button" class="btn btn-primary">Add Lecturer</button></a>
            </div>
            <div class="card-body px-3 px-md-5">
                @if (ViewBag.Success != null)
                {
                    <partial name="_Success" />
                }
                <div class="row">
                    @foreach (var lecturer in Model.Lecturers)
                    {
                        <div class="col-lg-6 col-xl-4 col-md-6 col-sm-12">
                            <div class="card card-default p-2">
                                <a href="javascript:0" class="media text-secondary" data-toggle="modal" data-target="#modal-lecturer-@lecturer.Id">
                                    <img src="@lecturer.ImagePath" class="mr-3 img-fluid rounded" alt="Avatar Image" />
                                    <div class="media-body">
                                        <h5 class="mt-0 mb-2 text-dark">@lecturer.FirstName @lecturer.LastName</h5>
                                        <ul class="list-unstyled text-smoke text-smoke">
                                            <li class="d-flex">
                                                <i class="mdi mdi-book mr-1"></i>
                                                <span>@lecturer.Courses[0].Name</span>
                                            </li>
                                            <li class="d-flex">
                                                <i class="mdi mdi-email mr-1"></i>
                                                <span>@lecturer.Email</span>
                                            </li>
                                            <li class="d-flex">
                                                <i class="mdi mdi-phone mr-1"></i>
                                                <span>@lecturer.Phone</span>
                                            </li>
                                        </ul>
                                    </div>
                                </a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>

        @foreach (var lecturer in Model.Lecturers)
        {

            <div class="modal fade" id="modal-lecturer-@lecturer.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header justify-content-end border-bottom-0">
                            <button id="delete-button" value="@lecturer.Id" class="btn-edit-icon">
                                <i class="mdi mdi-delete"></i>
                            </button>
                            <a asp-action="Details" asp-route-id="@lecturer.Id">
                                <button id="details-button" class="btn-edit-icon">
                                    <i class="mdi mdi-pencil"></i>
                                </button>
                            </a>
                            <button type="button" class="btn-close-icon" data-dismiss="modal" aria-label="Close">
                                <i class="mdi mdi-close"></i>
                            </button>
                        </div>

                        <div class="modal-body pt-0">
                            <div class="row no-gutters">
                                <div class="col-md-6">
                                    <div class="profile-content-left px-4">
                                        <div class="card text-center px-0 border-0">
                                            <div class="card-img mx-auto">
                                                <img class="rounded-circle" src="@lecturer.ImagePath" alt="user image" />
                                            </div>

                                            <div class="card-body">
                                                <h4 class="py-2">@lecturer.FirstName @lecturer.LastName</h4>
                                                <p>@lecturer.Email</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="lecturer-info px-4">
                                        <h4 class="mb-1">Lecturer Details</h4>
                                        <p class="text-dark font-weight-medium pt-4 mb-2">Email address</p>
                                        <p>@lecturer.Email</p>
                                        <p class="text-dark font-weight-medium pt-4 mb-2">Phone Number</p>
                                        <p>@lecturer.Phone</p>
                                        <p class="text-dark font-weight-medium pt-4 mb-2">Courses</p>
                                        @foreach (var course in lecturer.Courses)
                                        {
                                            <p>@course.Name, @course.Faculty, ECTS: @course.ECTS</p>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script type="text/javascript">
    const button = document.getElementById('delete-button');

    button.addEventListener('click', async _ => {
        await fetch('lecturers/delete/' + button.value, {
            method: 'delete'
        })
        @*console.log(button.value)*@
        location.reload();
    });
</script>

Day_52/EduWiki/EduWiki/Views/Shared/ErrorHandler.cshtml
@using System
@model Exception

<h1>@Model.Message</h1>

Day_52/EduWiki/EduWiki/Views/Shared/_Layout.cshtml
<html>
<head runat="Server">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" charset="utf-8">
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/site.css" rel="stylesheet" type="text/css" media="screen" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    @RenderBody()
</body>
</html>

Day_52/EduWiki/EduWiki/Views/Shared/_Success.cshtml
<span class="text-success">Object added succesfully</span>