Day_60/XSSPlayground/XSSPlayground/ViewModels/XSSViewModel.cs
namespace XSSPlayground.ViewModels
{
    public class XSSViewModel
    {
        public string Text { get; set; }
    }
}

Day_60/XSSPlayground/XSSPlayground/Controllers/PagesController.cs
using Microsoft.AspNetCore.Mvc;

namespace XSSPlayground.Controllers
{
    public class PagesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Day_60/XSSPlayground/XSSPlayground/Controllers/SecurityController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using XSSPlayground.ViewModels;

namespace XSSPlayground.Controllers
{
    public class SecurityController : Controller
    {
        private HtmlEncoder _htmlEncoder;
        private JavaScriptEncoder _javaScriptEncoder;
        private UrlEncoder _urlEncoder;

        public SecurityController(HtmlEncoder htmlEncoder, JavaScriptEncoder javaScriptEncoder, UrlEncoder urlEncoder)
        {
            _htmlEncoder = htmlEncoder;
            _javaScriptEncoder = javaScriptEncoder;
            _urlEncoder = urlEncoder;
        }

        public IActionResult XSSWithSecurityOff()
        {
            return View();
        }

        [HttpPost]
        public IActionResult XSSWithSecurityOff(XSSViewModel xssVM)
        {
            return View(xssVM);
        }

        public IActionResult XSSWithSecurityOn()
        {
            return View();
        }

        [HttpPost]
        public IActionResult XSSWithSecurityOn(XSSViewModel xssVM)
        {
            var text = _htmlEncoder.Encode(xssVM.Text);
            text = _javaScriptEncoder.Encode(text);

            xssVM.Text = text;

            return View(xssVM);
        }

        public IActionResult UrlEncode()
        {
            return View();
        }

        [HttpPost]
        public IActionResult UrlEncode(XSSViewModel xssVM)
        {
            xssVM.Text = _urlEncoder.Encode(xssVM.Text);
            return View(xssVM);
        }
    }
}

Day_60/XSSPlayground/XSSPlayground/Views/Security/UrlEncode.cshtml
@using XSSPlayground.ViewModels
@model XSSViewModel

<form method="post">
    Url:
    <input type="text" asp-for="@Model.Text" id="xss">
    <input type="submit" value="Submit">
</form>
Encoded url: @Model?.Text

Day_60/XSSPlayground/XSSPlayground/Views/Security/XSSWithSecurityOff.cshtml
@using XSSPlayground.ViewModels
@model XSSViewModel

<form method="post">
    სცადე &lt;script&gt;alert(1);&lt;/script&gt;
    <br />
    <input type="text" asp-for="@Model.Text" id="xss">
    <input type="submit" value="Submit">
</form>

Script:
<script>
    var xss = document.getElementById("xss").value;
    var pageMessage = xss ? xss : "";
    document.write(pageMessage);
</script>

Day_60/XSSPlayground/XSSPlayground/Views/Security/XSSWithSecurityOn.cshtml
@using XSSPlayground.ViewModels
@model XSSViewModel

<form method="post">
    სცადე &lt;script&gt;alert(1);&lt;/script&gt;
    <br />
    <input type="text" asp-for="@Model.Text" id="xss">
    <input type="submit" value="Submit">
</form>

Script:
@Model?.Text

Day_60/XSSPlayground/XSSPlayground/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - XSSPlayground</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Pages" asp-action="Index">XSSPlayground</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Pages" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Security" asp-action="XSSWithSecurityOff">Test XSS with no security</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Security" asp-action="XSSWithSecurityOn">Test XSS with security on</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Security" asp-action="UrlEncode">Encode URL</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - XSSPlayground - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>